### PR TITLE
Fixed ! that i have forget on 2 functions

### PR DESCRIPTION
**Pull request by dlion**
fixed if

### CODE REVIEW

**Comment by mrshu** [comment]
Thanks!

**Comment by mrshu** [comment]
Also, please note that I've renamed the function `pin_exist` to more specific `gpio_pin_exists`. This is to make sure that people can define they own `pin_exist` function if they want.

**Comment by dlion** [comment]
Also you have to change prototipe in the gpio.h file.

**Comment by mrshu** [comment]
Right, just did that.

Thanks!

**Pull request closed without merging**
