### PR TITLE
update Makefile

### PR DESCRIPTION
**Pull request by Jufino**

### CODE REVIEW

**Comment by mrshu** [comment]
Maybe we could also edit the Makefile so that it makes all the examples

E.g.

```
make examples
```

would make example_read and example_write

**Comment by Jufino** [comment]
ok, but I don`t know change makefile that make example - make example_read and example_write at one time

**Comment by mrshu** [comment]
You can create new rule in the Makefile. Something like

```
examples: example_read, example_write
```

This way the `make` command will build first `example_read` and then `example_write` in order to finish making `examples`

**Comment by Jufino** [comment]
Ok thanks

**Comment by mrshu** [comment]
Thanks again!

**Pull request merged**
